services:
  postgres:
    container_name: simple-shop-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge